version: '3'
services:
  db:
    image: postgres:15
    restart: always
    networks: 
      - default
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    expose: 
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - 13000:13000
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=todo_user
      - DB_PASSWORD=password123
      - DB_NAME=todo_db
    depends_on:
      - db

volumes:
  postgres_data:

